### ISSUE TITLE
Publish 0.9.0 on crates.io

### ISSUE THREAD

**Issue by rillian** [mozilla/mp4parse-rust#129]
It's been a while since we've made a release. This needs:
[x] [bump `mp4parse` version](https://github.com/mozilla/mp4parse-rust/pull/128)
[x] [publish `mp4parse_fallible`](https://github.com/alfredoyang/mp4parse_fallible/issues/1)
[x] `cargo publish` for each crate.
[x] Tag repo.

**Comment by alfredoyang** [comment]
We probably don't need to publish ```mp4parse_fallible``` because it is an optional dependency and included in Gecko build only.

**Comment by rillian** [comment]
It appears `cargo publish` requires all options to be published on crates.io. Probably this is so vendor mirrors (like we use in Firefox) have a complete picture and allow one to use all features. So we could only do this by patching out the fallible feature. That seems silly.

```
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: crates cannot be published to crates.io with dependencies sourced from a repository
either publish `mp4parse_fallible` as its own crate on crates.io and specify a crates.io version as a dependency or pull it into this repository and specify it with a path and version
(crate `mp4parse_fallible` has repository path `https://github.com/alfredoyang/mp4parse_fallible`)
```

**Comment by rillian** [comment]
I've now made the releases. I had some trouble with `cargo publish` and the virtual workspace, so I hacked the mp4parse_capi publication.
