### ISSUE TITLE
Replace custom log! implementation with env_logger

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/mp4parse-rust#139]
This only exists because it was a pain to use other crates inside Gecko when mp4parse was first developed, but now it's easier and we have many existing users of env_logger inside Gecko.

This came up when @bholley asked why we're using this while he was looking at reducing Debug trait use in release logging.

**Comment by djg** [comment]
Sounds like a good idea.

**Comment by bholley** [comment]
Replacing the existing log! macro to be a no-op eliminates 71 out of 389 remaining Debug impls in libxul.

Once we switch to env_logger, we should use debug! or trace! for anywhere we want {:?}, since those macros get compiled out in release builds.
