### ISSUE TITLE
Review use of Debug formatting and avoid in release-mode logging

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/mp4parse-rust#140]
Related to issue #139, @bholley is working on reducing Debug trait use in release builds (for code size reasons).  He proposed:

> what we do in stylo is use debug! and trace! for stuff where we need/want :?, and then avoid :? in info/warn/log which are compiled in release builds

So we'll need to review existing log! use and replace with debug!/trace! as necessary and remove any use of :? inside log!.

**Comment by rillian** [comment]
This should be addressed for mp4parse now. Thanks for filing!

**Comment by bholley** [comment]
Thanks for fixing!
