### ISSUE TITLE
Use nightly's try_reserve when available

### ISSUE THREAD

**Issue by snf** [mozilla/mp4parse-rust#146]
Fallible allocation API just went live in nightly and it's breaking the package because of a name conflict with mp4parse_fallible's try_reserve.
Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1446538

**Comment by kinetiknz** [comment]
I'll wait for try_reserve to hit stable before using it.  I'll leave this issue open to track that.

In the mean time, I've worked around the compilation failure with rustc nightly in https://github.com/mozilla/mp4parse-rust/commit/ded91a1661daaf55515e572aadd8e92e6d71cbaf.

**Comment by kinetiknz** [comment]
https://github.com/kinetiknz/mp4parse-rust/tree/issue146

But I'm still waiting for this feature to become stable.

**Comment by kinetiknz** [comment]
As a follow up to this, I've archived the mozilla/mp4parse_fallible repository since we no longer use it.
