### ISSUE TITLE
Implement `meta` parsing

### ISSUE THREAD

**Issue by chyyran** [mozilla/mp4parse-rust#150]
Apple's [QuickTime File Format](https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW1) is the closest to a standard to storing metadata in MP4 Boxes, and should be sub boxes of `trak`, `moov` or `mdia`

**Comment by kinetiknz** [comment]
Thanks for filing the issue.  There's no immediate need for this within Firefox, which is the primary consumer of mp4parse, so it's unlikely we'll implement this ourselves.  Would you be interested in contributing code and tests to add support for this?

**Comment by chyyran** [comment]
Finally got around to looking into this, and after some investigation it seems like `meta` is conventionally stored as a child of the `udta` box. Thus I'm planning to implement limited support for `meta` box parsing but only exposed when it is a child of the `udta` box.
