### ISSUE TITLE
Republish + regenerate documentation as API has changed

### ISSUE THREAD

**Issue by SingingTree** [mozilla/mp4parse-rust#170]
Since the docs were last generated the API has undergone some changes. Notably #163 has moved some data that was previously stored per track to per sample info (offering finer granularity). If we republish the lastest version of the crate the docs could be regenerated for the new version to avoid footguns (which I may have just shot myself with).

**Comment by kinetiknz** [comment]
Thanks for the reminder. I published 0.11.2 as-is.
