### ISSUE TITLE
Can this be used for replacing flv.js mp4-generator?

### ISSUE THREAD

**Issue by huangjj27** [mozilla/mp4parse-rust#177]
Hi! we are trying to make a wasm version of [flv.js](https://github.com/bilibili/flv.js), and I'm working on rewriting [flv.js' mp4generator.js](https://github.com/bilibili/flv.js/blob/master/src/remux/mp4-generator.js) in rust. Since this is my first time to work on mutimedia, I don't know much about how media is parsed. Would you give me some advice? thanks!

**Comment by jyavenard** [comment]
No it cannot. This project is only used to read the moov box that contains the metadata of a Mp4 file. It doesn't demux its content.

**Comment by huangjj27** [comment]
thanks!
