### ISSUE TITLE
Check for valid context on C API getters

### ISSUE THREAD

**Issue by baumanj** [mozilla/mp4parse-rust#195]
Functions like [`mp4parse_get_indice_table`](https://github.com/mozilla/mp4parse-rust/blob/bbb4a1217d2826e95b0a843e73c9e1a2faa23953/mp4parse_capi/src/lib.rs#L900) access data through a context object within the `parser` parameter. To help reduce the risk of this unsafe code, the context object could keep some state to indicate whether a a valid parse operation preceded the getter call rather than assuming good data from the C side.

If the C caller passed in uninitialized memory, there's no guarantee that it wouldn't match the field that marked a context as valid, but it would be much less likely.

**Comment by kinetiknz** [comment]
That's what Mp4parseParser::poisoned is intended for.  `mp4parse_get_indice_table` already tests it.  Are there cases you're thinking of that aren't covered by this?

That mechanism doesn't handle the C API receiving an invalid context pointer. We'd need to track valid pointers/handles returned from our API and reject anything else being passed in.  Not sure that's worth it, though.

**Comment by baumanj** [comment]
The case I'm imagining is different from `poisoned`, which gets set [when a context _becomes_ invalid](https://github.com/mozilla/mp4parse-rust/blob/63d4744905b0a918ed76461d0de48f8188325f6b/mp4parse_capi/src/lib.rs#L423). I'm thinking of the state when a context exists because [`mp4parse_new`](https://github.com/mozilla/mp4parse-rust/blob/63d4744905b0a918ed76461d0de48f8188325f6b/mp4parse_capi/src/lib.rs#L367) has been called, but that context isn't really valid because [`mp4_parse_read`](https://github.com/mozilla/mp4parse-rust/blob/63d4744905b0a918ed76461d0de48f8188325f6b/mp4parse_capi/src/lib.rs#L409) hasn't been called.

It would be possible to repurpose `poisoned` to handle this case by setting it to `true` to begin with and only setting it to false when `mp4_parse_read` returned successfully. Though in that case, it might make more sense to use a different name like `parsed_ok` or something. Or, perhaps it would make more sense to have `mp4parse_new` do the work that `mp4_parse_read` does as well (and remove `mp4_parse_read`) so that the C side would never have access to a context that didn't represent a validly parsed file.

**Comment by djg** [comment]
> Or, perhaps it would make more sense to have `mp4parse_new` do the work that `mp4_parse_read` does as well (and remove `mp4_parse_read`) so that the C side would never have access to a context that didn't represent a validly parsed file.

Surely, this.

**Comment by kinetiknz** [comment]
> The case I'm imagining is different from `poisoned`, [...]

Makes sense, sorry I didn't pick that up from your original comment.

> Or, perhaps it would make more sense to have `mp4parse_new` do the work that `mp4_parse_read` does as well (and remove `mp4_parse_read`) so that the C side would never have access to a context that didn't represent a validly parsed file.

Sounds good.  The existing use in Gecko would adapt to this easily.

**Comment by baumanj** [comment]
> Surely, this.

Ok https://github.com/mozilla/mp4parse-rust/pull/200 is up now.

And [don't call me Shirley](https://www.youtube.com/watch?v=KM2K7sV-K74).
