### ISSUE TITLE
Assert in `read_iloc` triggered by fuzzing

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/mp4parse-rust#212]
When the `avif` fuzz target is run long enough, eventually the [`debug_assert!` in `read_iloc`](https://github.com/mozilla/mp4parse-rust/blob/63ca8c6bde27b39dea87fb15e2922a23cb38c8df/mp4parse/src/lib.rs#L1630) is triggered.  It's not urgent, but it'd be nice to avoid this so the fuzzer can continue exploring.

In the case I hit, `item_count` is 0, so we skip the item reading loop and immediately hit the assert with `iloc.remaining()` returning 8.  Testcase saved locally, if required.

**Comment by baumanj** [comment]
I believe this is resolved by https://github.com/mozilla/mp4parse-rust/commit/4f4447ebdd8985efedcd5ef3235e312f9fc589c5, but please correct me if I'm mistaken.
