### ISSUE TITLE
Support for H.263 and MPEG4 codec.

### ISSUE THREAD

**Issue by dreamaniajp** [mozilla/mp4parse-rust#240]
Hi, current mp4parse doesn't support H.263 and MPEG-4 codec.
May I know if there is a plan to support these two codecs?
Or if you may accept that kind of contribution?

Thanks a lot.

**Comment by SingingTree** [comment]
Support for demuxing different data is usually driven by users of the lib contributing support. Firefox is a big one of these, and my understanding is that there's not a big use case for H.263 at this time. When you say MPEG-4 are we talking [MPEG-4 Part 2](https://en.wikipedia.org/wiki/MPEG-4_Part_2)? If so I think that would be in a similar boat.

If someone where willing to add support for those I don't see why it wouldn't be accepted.

**Comment by dreamaniajp** [comment]
Hi, I've filed a PR for H.263 support. https://github.com/mozilla/mp4parse-rust/pull/245
May I have someone's help to review?

Thanks a lot!

**Comment by SingingTree** [comment]
Thanks! I'm not super familiar with the H.263 packing, so am going to check the specification and will follow up with any questions on that PR. If you know the relevant specs it would be appreciated if you could point them out so I don't overlook any of them.

**Comment by dreamaniajp** [comment]
Thanks!
The specification could be found on ETSI site.
The latest one I could find is
https://www.etsi.org/deliver/etsi_ts/126200_126299/126244/13.05.00_60/ts_126244v130500p.pdf

Thanks a lot!

**Comment by baumanj** [comment]
Does https://github.com/mozilla/mp4parse-rust/pull/245 resolve this, or is there additional work to do?

**Comment by baumanj** [comment]
I assume this is done. Please reopen if not.
