### ISSUE TITLE
c196ca8 cause MP4Metadata.test_case_mp4 fails

### ISSUE THREAD

**Issue by ChunMinChang** [mozilla/mp4parse-rust#261]
`MP4Metadata.test_case_mp4` fails when updating `mp4parse-rust` crate. See failure here: https://treeherder.mozilla.org/logviewer?job_id=324286421&repo=autoland&lineNumber=29156 in [BMO 1681811](https://bugzilla.mozilla.org/show_bug.cgi?id=1681811).The first bad commit is commit c196ca8. The changes are made in #252. Now it blocks the avif-transparency support ([BMO 1654462](https://bugzilla.mozilla.org/show_bug.cgi?id=1654462)).

The error occurs in [these lines](https://searchfox.org/mozilla-central/rev/0bcf81557b89e7757c44e25bb4bc7f4cb8619dc9/dom/media/gtest/mp4_demuxer/TestParser.cpp#280,283,336). The test file is [`test_case_1185230.mp4`](https://searchfox.org/mozilla-central/rev/0bcf81557b89e7757c44e25bb4bc7f4cb8619dc9/dom/media/gtest/mp4_demuxer/TestParser.cpp#187). The error indicates [`MP4Metadata::GetNumberTracks`](https://searchfox.org/mozilla-central/rev/0bcf81557b89e7757c44e25bb4bc7f4cb8619dc9/dom/media/gtest/mp4_demuxer/TestParser.cpp#280,283,336) and [`MP4Metadata::GetTrackInfo`](https://searchfox.org/mozilla-central/rev/0bcf81557b89e7757c44e25bb4bc7f4cb8619dc9/dom/media/gtest/mp4_demuxer/TestParser.cpp#325,331,336) don't work as what it's expected. The underlying calls used in `MP4Metadata::GetNumberTracks` and `MP4Metadata::GetTrackInfo` are `mp4parse_get_track_count`, `mp4parse_get_track_info`, `mp4parse_get_track_audio_info`, and `mp4parse_get_track_video_info`. All the errors are around `track`.

I am not familiar with mp4 stuff enough to identify the problem quickly. But I guess there might be some mistakes around `read_mp4` and `read_moov`. It seems the track-info is loaded there. The `context` is changed from an input `&mut MediaContext` to an output `Result<MediaContext>`. Not sure if it causes the problem. Any idea?

**Comment by baumanj** [comment]
See https://github.com/mozilla/mp4parse-rust/pull/263
