### ISSUE TITLE
support MPEG-2 layer 3 codec ID

### ISSUE THREAD

**Issue by nbeisert** [mozilla/mp4parse-rust#274]
MP3 audio streams with sampling rates 24000/22050/16000 are not identified correctly (and consequently MP4 videos with low-frequency audio are muted in firefox). Would you mind adding the ID 0x69 for the MPEG-2 layer 3 codec? I believe this could be achieved by replacing `0x6B` by `0x69 | 0x6B` in:
https://github.com/mozilla/mp4parse-rust/blob/3011a2b923c8b0f1b392bcdd008cd8b95ffd846b/mp4parse/src/lib.rs#L3335

**Comment by baumanj** [comment]
Could you provide an example file that demonstrates the issue, @nbeisert ?

**Comment by nbeisert** [comment]
Sorry, I should have provided a link to the bug at firefox bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=986926

Here are three files based on the audio file of the other bug report:
https://user-images.githubusercontent.com/2470595/107852947-c4caef80-6e13-11eb-92eb-de4cf07c2bd3.mp4 (22 kHz; does not work)
https://user-images.githubusercontent.com/2470595/107852954-cb596700-6e13-11eb-8049-731093a0fad6.mp4 (44 kHz; works)
https://user-images.githubusercontent.com/2470595/107852956-cd232a80-6e13-11eb-8573-cf1f745c9f03.mp4 (22 kHz patched stream type 0x69 to 0x6B; works)

Here's a bash script to generate the above sample mp4 files: 
```
ffmpeg -i owl.22khz.vbr.mp3 -vn -c:a mp3 -ar 22050 -y owl22.mp4
ffmpeg -i owl.22khz.vbr.mp3 -vn -c:a mp3 -ar 44100 -y owl44.mp4
pos=$(grep -a -o -b esds owl22.mp4)
pos=${pos%:*}
pos=$(( pos+21 ))
cp owl22.mp4 owl22patch.mp4
echo -n -e '\x6B' | dd of=owl22patch.mp4 obs=1 seek=$pos conv=notrunc bs=1 count=1
```

**Comment by baumanj** [comment]
I confirmed that change seems to be sufficient to fix the issue. Thanks for the help!

**Comment by nbeisert** [comment]
Great! Glad I could help...
