### ISSUE TITLE
read adaptor for mp4_demuxer::Stream

### ISSUE THREAD

**Issue by rillian** [mozilla/mp4parse-rust#3]
While our initial target is to parse metadata for MSE, the gecko interface expects a stream, so we need to implement some kind of adaptor which implements `Read` on the rust side and calls back to an `mp4_demuxer::Stream` on the C++ side.

https://dxr.mozilla.org/mozilla-central/source/media/libstagefright/binding/include/mp4_demuxer/Stream.h

**Comment by rillian** [comment]
Might make more sense to keep this code in gecko, where it has access to the requisite C++ header.

**Comment by kinetiknz** [comment]
Fixed by 20d81a92487a9aeeacd3c798b521a92a8d8ffebb.
