### ISSUE TITLE
Implement `esds` parsing

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/mp4parse-rust#30]
The `media.rust.test_mode` pref in Gecko found another mismatch between mp4parse and libstagefright.  From a Facebook live stream, a `moov` with a video and audio track results in mp4parse returning a samplerate of 44100 and libstagefright returning a samplerate of 22050.

mp4parse is parsing the samplerate directly from the `mp4a`.  libstagefright prefers the value from the `esds`.

**Comment by alfredoyang** [comment]
hmm... it looks like not just audio sample rate but also channel count needs to be retrieved from esds in Facebook video. I'll have another PR for it.

**Comment by jyavenard** [comment]
Actually, 44.1kHz would be the value to use. The ESDS value returned is of the AAC-LC stream. 
Facebook uses HE-AAC v2. 

Sampling rate would be twice as much as the LC stream. 

The stage fright returns the sampling rate of the LC stream is an absolute pain in the arse as it requires to decode the first sample to get the real sampling rate. 

Ideally, for AAC, the AudioSpecificConfig should be decoded and detect the presence of SBR. 

The sampling rate value found in the ESDS Is useless

**Comment by rillian** [comment]
@jyavenard So we should drop the ESDS value from both the rust and stagefright parsers?

**Comment by kinetiknz** [comment]
At this stage we're trying to match stagefright's behaviour (as observable via the API we're using in the MP4Metadata class) so that mp4parse-rust works as a drop-in replacement.  Making different choices for which metadata to expose and from which source is possible and may make sense in the future, but it's outside the scope of what we're trying to do here.

**Comment by kinetiknz** [comment]
Closing as obsolete.  PR #38 added ESDS parsing and PR #39 addressed the functionality this issue was about (matching behaviour with libstagefright).
