### ISSUE TITLE
What's the purpose of `TABLE_SIZE_LIMIT`?

### ISSUE THREAD

**Issue by AdrianEddy** [mozilla/mp4parse-rust#310]
I've ran into `OutOfMemory` errors when parsing a file. Besides this error being confusing, I tracked it down to checking the `TABLE_SIZE_LIMIT` for `stts` sample count. That file is a regular file from Sony RX0II camera, with a length of `6:23`. Audio track sample count is `18 402 480` with sample delta `1`, and this exceeded the `TABLE_SIZE_LIMIT` variable causing the `OutOfMemory` error.

I could just make a PR increasing this limit, but I'm pretty sure someone will run into this issue again sooner or later.
So my question is: What is the purpose of this limit? Why don't we just rely on TryVec and failing to allocate if we are indeed out of memory?

**Comment by baumanj** [comment]
Based on [this PR](https://github.com/mozilla/mp4parse-rust/pull/97) and [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1367508) it references, I believe it was introduced before we had support for fallible allocation in our collection types. That appears that [it was added a few months later](https://github.com/mozilla/mp4parse-rust/commit/c9a4a1c1912b23caf72e6a6f071aef489a48f24b).

At this point, we should be using [`fallible_collections`](https://github.com/vcombey/fallible_collections) for everything, so my guess is `TABLE_SIZE_LIMIT` can be removed, but this was before my time, so I'll defer to @kinetiknz, who was around then.
