### ISSUE TITLE
Include license and readme in crate source

### ISSUE THREAD

**Issue by remilauzier** [mozilla/mp4parse-rust#313]
Hi. Fedora would like to have a readme and a license file for packaging.
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation

**Comment by baumanj** [comment]
If [LICENSE](https://github.com/mozilla/mp4parse-rust/blob/master/LICENSE) and [README.md](https://github.com/mozilla/mp4parse-rust/blob/master/README.md) aren't sufficient, can you submit a PR for the changes Fedora would need?

**Comment by baumanj** [comment]
Got it. I'm looking into whether that would cause any problems on our side. Assuming not, I'll make that change, but it may take a little bit since lots of folks are taking vacation at the moment.

**Comment by baumanj** [comment]
Will https://github.com/mozilla/mp4parse-rust/pull/317 suffice for your needs, @remilauzier ?

**Comment by remilauzier** [comment]
Yeah. That should work.
