### ISSUE TITLE
Test failed in fedora copr

### ISSUE THREAD

**Issue by remilauzier** [mozilla/mp4parse-rust#315]
https://download.copr.fedorainfracloud.org/results/remilauzier/zemeroth/fedora-rawhide-x86_64/02303760-rust-mp4parse/builder-live.log.gz

---- public_video_cbcs stdout ----
thread 'public_video_cbcs' panicked at 'Unknown file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', tests/public.rs:513:49

**Comment by baumanj** [comment]
It looks like something about the way the sources are getting processed is failing to include the test files in the expected location. Can you upload an archive of the directory that this command is executing on?
```
+ /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 /usr/bin/cargo test -j2 -Z avoid-dev-deps --release --no-fail-fast
```

**Comment by remilauzier** [comment]
[mp4parse-0.11.5.zip](https://github.com/mozilla/mp4parse-rust/files/6718006/mp4parse-0.11.5.zip)

**Comment by remilauzier** [comment]
It seem that a lot of test file are not include in the crate that fedora must download.

**Comment by baumanj** [comment]
Agreed. I'm not sure why that's the case, but it appears to be an issue with the way that fedora is processing the repo, not with the repo itself, so I'm going to close this.

**Comment by kinetiknz** [comment]
This is due to the [`Cargo.toml` exclude](https://github.com/mozilla/mp4parse-rust/blob/9a5173c9b4fa60c6359421940a151544d2495557/mp4parse/Cargo.toml#L20), which was added to avoid making the published crates larger than necessary.
