### ISSUE TITLE
Unreleased conformance changes?

### ISSUE THREAD

**Issue by kornelski** [mozilla/mp4parse-rust#334]
I'm getting reports that my AVIF serializer doesn't work with Firefox 92, but my tests against mp4parse pass. Did you make any conformance changes that aren't on crates.io?

**Comment by kornelski** [comment]
I see there are lots of changes, so I've stopped using the crates.io version.

**Comment by baumanj** [comment]
Indeed we haven't been updating the crates.io version actively, and probably we should be. My apologies for that. I'll make an effort to update crates.io more regularly, but this repository will still be the best source to test against for early warning of changes.

**Comment by kornelski** [comment]
No problem. I've changed to using the repo.
