### ISSUE TITLE
question: extracting GPS metadata ?

### ISSUE THREAD

**Issue by yuribudilov** [mozilla/mp4parse-rust#365]
hello everyone, happy 2022.

I have a **question**: I have a lot of MP4 and MOV video files (sources: Android phones and Apple iPhones).

I want to extract the GPS latitude/longitude coordinates and date/time when the video was taken from them, using Rust.

Can I do this using this crate?

Currently I use **exiftool** command line utility to do this but I want to be able to do it directly from a Rust program (or worst case, from C API).

**Comment by baumanj** [comment]
No, that's not something that's currently supported. We may accept a patch, though. Are you interested in implementing it?

**Comment by baumanj** [comment]
From a quick search of crates.io, https://crates.io/crates/kamadak-exif may provide what you want. I don't have any experience with it, so I can't provide a recommendation either way.

**Comment by yuribudilov** [comment]
I thank you very much!! 
I will take anything that works directly from Rust. If it is a easy-to-use Rust FFI wrapper, it will do also.

So far, embarrassingly enough for Rust, LOL, I had to use Perl utility exittool to extract GPS and other metadata and save the output on text file. Then I use Rust to parse output file. It works, but it is slow and totally unsatisfying solution. 
So if there is a pure Rust solution to handle MP4 and MOV then I am 1000% for it.
