### ISSUE TITLE
crates.io release?

### ISSUE THREAD

**Issue by mattfbacon** [mozilla/mp4parse-rust#387]
The last crates.io release was 0.12 but this repo is on 0.16. Could you release the new version on crates.io?

**Comment by fintelia** [comment]
This is going to become more urgent once rustc 1.70 is released on June 1st and the crates.io version stops compiling: https://github.com/mozilla/mp4parse-rust/issues/405#issuecomment-1556294196

**Comment by est31** [comment]
Ideally, there would also be a fix for the 0.12.0 version, via a 0.12.1 release, so that users can upgrade to 0.16 at their own schedule.

**Comment by fintelia** [comment]
Tagging @baumanj who published the previous crates.io releases

**Comment by kinetiknz** [comment]
Apologies for the delay and build breakage.  I've published 0.12.1 containing https://github.com/mozilla/mp4parse-rust/commit/8d58b2d5fc7f552d585964354d8269bcca3d9251 and 0.17.0 based on the current master branch to crates.io now.
