### ISSUE TITLE
Update public.rs

### ISSUE THREAD

**Issue by rillian** [mozilla/mp4parse-rust#60]
We've added a bunch of public structs and members since public.rs was written. Probably we should update that at least so we're clear if we need to bump semver because we removed a public interface.

**Comment by baumanj** [comment]
Per https://semver.org/#spec-item-4:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Since we're currently at 0.11.4 in both the [`mp4parse` crate](https://github.com/mozilla/mp4parse-rust/blob/f7c35a30ff25521bebe64c19d3f306569ecb5385/mp4parse/Cargo.toml#L3) and the [`mp4parse_capi` crate](url), we have no semver restrictions on changes.
