### ISSUE TITLE
Support rev 1.0 vpcc box

### ISSUE THREAD

**Issue by rillian** [mozilla/mp4parse-rust#93]
Since FFmpeg's commit 64ad44a381 (https://github.com/FFmpeg/FFmpeg/commit/64ad44a381), Firefox no longer plays vp9 in mp4 files.

This commit updates the vpcc box to be per 1.0 spec:

https://github.com/webmproject/vp9-dash/blob/master/VPCodecISOMediaFileFormatBinding.md

(from https://bugzilla.mozilla.org/show_bug.cgi?id=1365787)

**Comment by est31** [comment]
Can this be closed now?

**Comment by kinetiknz** [comment]
Yeah, thanks for pointing it out.  Done in #96.
